Added functionality to have grid and battery display daily imported/exported power
flixlix/power-flow-card-plus pull request #116
Opened 2023-04-21 14:16 UTC by xsirpreisx

Hey there,

as I mentioned, I started implementing an option to add daily imported and exported power to the grid and battery circles.

I added two new configuration options to grid and battery: energy_exported_info and energy_imported_info

Configuration can look like this:

```
type: custom:power-flow-card-plus
entities:
  home:
    color_icon: true
    secondary_info:
      entity: sensor.solar_house_consumption_daily
      unit_of_measurement: kWh
  grid:
    entity:
      consumption: sensor.solar_grid_to_house_w
      production: sensor.solar_panel_to_grid_w
    display_state: one_way
    color_icon: true
    energy_exported_info:
      entity: sensor.solar_exported_power_daily
      unit_of_measurement: kWh
    energy_imported_info:
      entity: sensor.solar_imported_power_daily
      unit_of_measurement: kWh
  solar:
    entity: sensor.solar_panel_production_w
    color_icon: true
    secondary_info:
      entity: sensor.solar_panel_production_daily
      unit_of_measurement: kWh
  battery:
    entity:
      consumption: sensor.solar_battery_to_house_w
      production: sensor.solar_battery_in_w
    state_of_charge: sensor.solaredge_b1_state_of_energy
    display_state: one_way
    color_icon: true
    color:
      production: '#fc888b'
    energy_exported_info:
      entity: sensor.solar_battery_out_daily
      unit_of_measurement: kWh
    energy_imported_info:
      entity: sensor.solar_battery_in_daily
      unit_of_measurement: kWh
```

This will produce something like can be seen in the following screenshot:

![image](https://user-images.githubusercontent.com/37976738/233658103-101795d6-617c-4e23-a68e-d687a77de5ea.png)

If used, the grid and battery icons will be moved over to the side and a smaller size is used.

This will, because of size issues, only work when using "one_way".

Coloring is not yet possible. I could implement that in the future. Styling/CSS is also not perfect yet. But this is a good start. 

Let me know what you think.

2023-04-26 06:59 UTC, flixlix commented
Thank you for this PR! I will review it later

2023-04-27 15:19 UTC, flixlix requested changes
Hey there,
thank you once again for your PR.
Sorry I didn't review this PR earlier. I've been pretty busy.

I tried commenting on the most important points.

I'm afraid there is not enough space currently inside of the circles, and I would like to keep the size of them consistent with the size of the original energy distribution card.
Even if there was enough space, I think this just looks too crowded.

I did notice you made a release in your fork, that's fine by me :)

2023-04-27 18:08 UTC, xsirpreisx commented on src/power-flow-card-plus.ts
> +
Isn't that the case for the other values as well? What if someone configured secondary info that's >999 kWh? That probably wouldn't look all to good either?

Importing or exporting 1000 kWh is also kind of hard to do, I guess :-D

2023-04-27 18:08 UTC, xsirpreisx commented on src/power-flow-card-plus.ts
> +    const hasGridImportedPower =
That's a very valid point. I do know the difference between energy and power, and I am not sure why I used 'power' everywhere.

2023-04-27 18:12 UTC, xsirpreisx commented
> Hey there, thank you once again for your PR. Sorry I didn't review this PR earlier. I've been pretty busy.
> 
> I tried commenting on the most important points.
> 
> I'm afraid there is not enough space currently inside of the circles, and I would like to keep the size of them consistent with the size of the original energy distribution card. Even if there was enough space, I think this just looks too crowded.
> 
> I did notice you made a release in your fork, that's fine by me :)

Thanks for reviewing. 

I do somewhat disagree a little bit here. "Not enough space inside the circles" is only true if users tried displaying data that's not supposed to be there. It does look a little bit crowded, I'll give you that, but you get used to it rather quickly. I have been using my release for a while now and it's not bothering me that it's a little more crowded than it used to be. It also show more information and I don't have to scroll and look in other places any longer to find my imported and exported kWh.

Also, it's optional. If users want "not crowded", they aren't obliged to use this functionality.

2023-04-28 09:22 UTC, Ryanmt2 commented
+1 this is a missing and valuable feature. It should be disabled by default perhaps but I came here specifically looking to do this. 

Due to the way my systems works the live wattage is not that interesting, the lag between the inverter reporting and the rest of the sensors means on a day with passing clouds the values are massively out of sync. Displaying the accumulated score like the energy dashboard but with all the configuration options would be awesome.

2023-05-05 22:41 UTC, flixlix commented
Are you willing to do the changes I sent in the Review?

2023-05-07 09:13 UTC, xsirpreisx commented
> Are you willing to do the changes I sent in the Review?

I can do that. Not sure when I'll get to it, but I'll try.

2023-05-19 21:20 UTC, flixlix commented
Closing for now due to the release of my [Energy Flow Card Plus](https://github.com/flixlix/energy-flow-card-plus). Feel free to apply the changes and I'll check it once again

2023-05-19 21:20 UTC, closed without merging